# 1. a. i. O(1)
#       ii. O(N + 1)
#       iii. O(N)
#       iv. O(N + 2)
#    b. i. O(1)
#       ii. O(N + 2)
#       iii. O(N)
#       iv. O(N + 1)
#    c. i. O(1)
#       ii. O(N + 1)
#       iii. O(N)
#       iv. O(log N)
#       v. O(N + 1)
#   2. O(1), O(log n), O(n^-2), O(n), O(n^2), O(n^3), O(n^n)
#   3. a. O(n)
#      b. O(log n)
#      c. O(n)
#      d. O(log n)
#      e. O(1)

